name: signalsfeb2020
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - pandas
  - python=3.7.4
  - scikit-image=0.16.1
